# Generated by Django 4.1.7 on 2023-03-10 22:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
