# Generated by Django 4.1.7 on 2023-03-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='deadline',
            new_name='apply_by_date',
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected')], max_length=200, null=True),
        ),
    ]
