# Generated by Django 4.1.7 on 2023-02-28 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('applications', models.ManyToManyField(to='api.application')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.ManyToManyField(to='api.coverletter'),
        ),
        migrations.AddField(
            model_name='application',
            name='curriculum_vitae',
            field=models.ManyToManyField(to='api.curriculumvitae'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile'),
        ),
    ]
