# Generated by Django 4.1.7 on 2023-03-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_deadline_job_apply_by_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='apply_by_date',
            new_name='deadline',
        ),
    ]
