version: 2.1

orbs:
  cypress: cypress-io/cypress@3
#  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout

      #- sonarcloud/scan

      - run: 
          name: Install backend requirements
          command: |
            cd CareerConnect_API 
            pip install -r requirements.txt

      - run:
          name: Run backend_tests
          command: |
            cd CareerConnect_API/
            python manage.py test

      - run: 
          name: Install frontend requirements
          command: |
            cd frontend
            npm install

      - run: 
          name: Run frontend_tests
          command: |
            cd CareerConnect_API/
            npm run test
            
      # -run:
      #     name: Run Frontend_tests

workflows:
  build_and_scan:
    jobs:
      - build #:
          #context: sonarCloud