version: 2.1

orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5.0.2
#  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  test_backend:
    docker:
      - image: python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: Install backend requirements
          command: |
            cd CareerConnect_API 
            pip install -r requirements.txt

      - run:
          name: Run backend_tests
          command: |
            cd CareerConnect_API/
            python manage.py test

  test_frontend:
    executor: node/default
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Xvfb
          command: |
            sudo apt-get update
            ps -e | grep -e apt -e adept | grep -v grep
            rm /var/lib/dpkg/lock 
            sudo apt-get install -y xvfb
      - run: 
          command: apt-get install xvfb
          name: Installing xvfb dependency
      - node/install-packages:
          app-dir: ~/repo/frontend
          pkg-manager: yarn
      - run:
          command: cd frontend && yarn run test
          name: Run tests

workflows:
  # cypress-orb:
  #   jobs:
  #   working_directory: ~/repo
  #     - cypress/run:
  #         cypress-command: cd frontend && npx cypress run --component
  build_and_scan:
    jobs:
      - test_backend #:
          #context: sonarCloud
      - test_frontend #:
        