import {Option} from "./types";

export const filterRadioOptions:Option[] = [
    {id: 0, name: "All Offers"},
    {id: 1, name: "Most Relevant"},
    {id: 2, name: "Recommended"},
    {id: 4, name: "Active Jobs"}
]

export const sortByOptions: Option[] = [
    { id: 0, name: "Relevance"},
    { id: 1, name: "Date Posted: Newest First" },
    { id: 2, name: "Date Posted: Oldest First" },
    { id: 3, name: "Deadline: Newest First" },
    { id: 4, name: "Deadline: Oldest First" },
    { id: 5, name: "Salary: Low to High" },
    { id: 6, name: "Salary: High to Low" },
];

export const industryOptions: Option[] = [
    { id: 0, name: "Accounting" },
    { id: 1, name: "Advertising" },
    { id: 2, name: "Aerospace" },
    { id: 3, name: "Agriculture" },
    { id: 4, name: "Architecture" },
    { id: 5, name: "Arts & Entertainment" },
    { id: 6, name: "Automotive" },
    { id: 7, name: "Banking" },
    { id: 8, name: "Beauty & Cosmetics" },
    { id: 9, name: "Biotech" },
    { id: 10, name: "Broadcasting" },
    { id: 11, name: "Business" },
    { id: 12, name: "Chemical" },
    { id: 13, name: "Construction" },
    { id: 14, name: "Consulting" },
    { id: 15, name: "Consumer Goods" },
    { id: 16, name: "Design" },
    { id: 17, name: "Education" },
    { id: 18, name: "Energy" },
    { id: 19, name: "Engineering" },
    { id: 20, name: "Environmental" },
    { id: 21, name: "Fashion" },
    { id: 22, name: "Finance" },
    { id: 23, name: "Food & Beverage" },
    { id: 24, name: "Government" },
    { id: 25, name: "Healthcare" },
    { id: 26, name: "Hospitality" },
    { id: 27, name: "Human Resources" },
    { id: 28, name: "Insurance" },
    { id: 29, name: "Internet" },
    { id: 30, name: "Law Enforcement" },
    { id: 31, name: "Legal" },
    { id: 32, name: "Manufacturing" },
    { id: 33, name: "Marketing" },
    { id: 34, name: "Media" },
    { id: 35, name: "Mining" },
    { id: 36, name: "Nonprofit" },
    { id: 37, name: "Pharmaceuticals" },
    { id: 38, name: "Public Relations" },
    { id: 39, name: "Real Estate" },
    { id: 40, name: "Retail" },
    { id: 41, name: "Technology" },
    { id: 42, name: "Telecommunications" },
    { id: 43, name: "Transportation" },
    { id: 44, name: "Travel" },
    { id: 45, name: "Utilities" },
    { id: 46, name: "Venture Capital" },
    { id: 47, name: "Veterinary" },
    { id: 48, name: "Warehousing" },
    { id: 49, name: "Wholesale" },
    { id: 50, name: "Wine and Spirits" },
    { id: 51, name: "Wireless" },
    { id: 52, name: "Writing and Editing" }
]