import { IJob, JobType } from "./types";
import { loremIpsum } from "lorem-ipsum";

const generateLorem = () => loremIpsum({
    count: 10,                // Number of "words", "sentences", or "paragraphs"
    format: "plain",         // "plain" or "html"
    paragraphLowerBound: 4,  // Min. number of sentences per paragraph.
    paragraphUpperBound: 7,  // Max. number of sentences per paragarph.
    sentenceLowerBound: 6,   // Min. number of words per sentence.
    sentenceUpperBound: 15,  // Max. number of words per sentence.
    suffix: "\r\n\n",            // Line ending, defaults to "\n" or "\r\n" (win32)
    units: "paragraphs",      // paragraph(s), "sentence(s)", or "word(s)"
})

export const mockJobs: IJob[] = [
    {
        id: 1,
        title: "Software Engineer",
        types: [JobType.FULL_TIME],
        short_description: "We are looking for a software engineer to join our team.",
        description: generateLorem(),
        location: "San Francisco, CA",
        company: "Apple Inc.",
        salary: 100000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 2,
        title: "Marketing Manager",
        types: [JobType.FULL_TIME, JobType.PERMANENT],
        short_description: "We are looking for a marketing manager to lead our team.",
        description: generateLorem(),
        location: "New York, NY",
        company: "Amazon.com Inc.",
        salary: 80000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 3,
        title: "Graphic Designer",
        types: [JobType.PART_TIME],
        short_description: "We are looking for a graphic designer to work on a part-time basis.",
        description: generateLorem(),
        company: "Alphabet Inc.",
        location: "Los Angeles, CA",
        salary: 50000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 4,
        title: "Product Manager",
        types: [JobType.FULL_TIME],
        short_description: "We are looking for a product manager to join our team.",
        description: generateLorem(),
        company: "Facebook Inc.",
        location: "Seattle, WA",
        salary: 120000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 5,
        title: "Sales Representative",
        types: [JobType.CONTRACT],
        short_description: "We are looking for a sales representative to work on a contract basis.",
        description: generateLorem(),
        company: "IBM Corporation",
        location: "Chicago, IL",
        salary: 50000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 6,
        title: "Data Analyst",
        types: [JobType.FULL_TIME, JobType.REMOTE],
        short_description: "We are looking for a data analyst to join our team.",
        description: generateLorem(),
        company: "Intel Corporation",
        location: "San Francisco, CA",
        salary: 90000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 7,
        title: "HR Coordinator",
        types: [JobType.TEMPORARY],
        short_description: "We are looking for an HR coordinator to work on a temporary basis.",
        description: generateLorem(),
        company: "Microsoft Corporation",
        location: "Boston, MA",
        salary: 60000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 8,
        title: "Content Writer",
        types: [JobType.FREELANCE],
        short_description: "We are looking for a content writer to work on a freelance basis.",
        description: generateLorem(),
        company: "Oracle Corporation",
        location: "Austin, TX",
        salary: null,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 9,
        title: "IT Support Specialist",
        types: [JobType.FULL_TIME],
        short_description: "We are looking for an IT support specialist to join our team.",
        description: generateLorem(),
        company: "Samsung Electronics Co., Ltd.",
        location: "Portland, OR",
        salary: 70000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
    {
        id: 10,
        title: "Customer Service Representative",
        types: [JobType.PART_TIME, JobType.REMOTE],
        short_description: "We are looking for a customer service representative to work part-time and remotely.",
        description: generateLorem(),
        company: "Tesla, Inc.",
        location: "Miami, FL",
        salary: 35000,
        postedDate: new Date("2022-02-01"),
        applyByDate: new Date("2022-03-01"),
        contactEmail: "jobs@example.com",
        contactPhone: null,
        website: "https://example.com/jobs",
        companyLogoUrl: "https://example.com/logo.png",
    },
]


